# Generated by Django 5.1.4 on 2024-12-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='descricao',
            new_name='mensagem',
        ),
    ]
