# Generated by Django 5.1.4 on 2025-01-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='foto_do_Produto_Encomendado',
        ),
    ]
