# Generated by Django 5.1.4 on 2024-12-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='disponibilidade',
            new_name='Novidade',
        ),
        migrations.RenameField(
            model_name='encomenda',
            old_name='disponibilidade',
            new_name='Novidade',
        ),
    ]
