# Generated by Django 5.1.4 on 2024-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_disponibilidade_cardapio_novidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='nome_da_pessoa',
            field=models.CharField(default='Definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomenda',
            name='numero_de_telefone',
            field=models.CharField(default='Definir', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='foto_do_produto',
            field=models.ImageField(blank=True, null=True, upload_to='media/Cardapio'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='foto_do_Produto_Encomendado',
            field=models.ImageField(blank=True, null=True, upload_to='media/Encomendas'),
        ),
    ]
