# Generated by Django 5.1.4 on 2025-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_encomenda_foto_do_produto_encomendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_do_produto',
            field=models.ImageField(blank=True, null=True, upload_to='Cardapio'),
        ),
    ]
