# Generated by Django 5.1.4 on 2024-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_encomenda_nome_da_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
