# Generated by Django 5.1.4 on 2024-12-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_encomenda_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
