# Generated by Django 5.1.4 on 2024-12-29 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_encomenda_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data_da_e_hora_da_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
