# Generated by Django 5.1.4 on 2024-12-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_encomenda_data_da_e_hora_da_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='data_da_e_hora_da_compra',
            new_name='data_e_hora_da_compra',
        ),
    ]
