# Generated by Django 5.1.4 on 2024-12-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_rename_data_da_e_hora_da_compra_encomenda_data_e_hora_da_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='Novidade',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
