# Generated by Django 5.1.4 on 2025-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_foto_do_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartao'), ('dinheiro', 'Dinheiro')], default='pix', max_length=50),
        ),
    ]
