# Generated by Django 5.1.4 on 2024-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_encomenda_novidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='Novidade',
            field=models.BooleanField(default=False),
        ),
    ]
