# Generated by Django 5.1.4 on 2025-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_encomenda_forma_de_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='Novidade',
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('cartao', 'Cartao'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], default='pix', max_length=50),
        ),
    ]
