# Generated by Django 5.1.4 on 2024-12-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_encomenda_novidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='Forma_de_Pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('pebito', 'Debito'), ('predito', 'Credito'), ('dinheiro', 'Dinheiro')], default='pix', max_length=50),
        ),
    ]
