# Generated by Django 5.1.4 on 2025-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_remove_encomenda_novidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='descricao',
            field=models.CharField(max_length=3000),
        ),
    ]
