# Generated by Django 5.1.4 on 2025-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_e_hora_da_encomenda',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
