# Generated by Django 5.1.4 on 2025-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_encomenda_data_e_hora_da_encomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='endereço_da_entrega',
            field=models.CharField(max_length=100),
        ),
    ]
