# Generated by Django 5.1.4 on 2024-12-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_rename_forma_de_pagamento_encomenda_forma_de_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='Forma_de_Pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('debito', 'Debito'), ('credito', 'Credito'), ('dinheiro', 'Dinheiro')], default='pix', max_length=50),
        ),
    ]
