# Generated by Django 5.1.4 on 2025-01-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_encomenda_endereço_da_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='preco',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='estoque',
        ),
    ]
