# Generated by Django 5.1.4 on 2025-01-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_rename_preco_encomenda_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='avaliacao',
        ),
    ]
