# Generated by Django 5.1.4 on 2025-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_rename_forma_de_pagamento_encomenda_forma_de_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('avaliacao', models.TextField()),
                ('estoque', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('novidade', models.BooleanField()),
                ('foto_do_produto', models.ImageField(blank=True, null=True, upload_to='media/Cardapio')),
            ],
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
