# Generated by Django 5.1.4 on 2025-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_remove_encomenda_descricao_remove_produto_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='data_e_hora_da_encomenda',
            new_name='data_e_hora_da_entrega',
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='Produto_reservado',
            field=models.CharField(max_length=3000),
        ),
    ]
