# Generated by Django 5.1.4 on 2025-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_rename_data_e_hora_da_encomenda_encomenda_data_e_hora_da_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='numero_de_telefone',
            field=models.TextField(max_length=15),
        ),
    ]
