# Generated by Django 5.1.4 on 2025-01-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_cardapio_foto_do_produto_and_more'),
        ('produtos', '0016_produto_delete_cardapio'),
    ]

    operations = [
    ]
