# Generated by Django 5.1.4 on 2025-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_alter_encomenda_numero_de_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='Produto_reservado',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='numero_de_telefone',
            field=models.CharField(max_length=15),
        ),
    ]
