# Generated by Django 5.1.4 on 2025-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_alter_encomenda_produto_reservado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=3000),
        ),
    ]
