# Generated by Django 5.1.4 on 2025-02-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encomenda',
            old_name='Produto_reservado',
            new_name='produtos_encomendados',
        ),
    ]
