# Generated by Django 6.0 on 2026-06-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_rename_produto_reservado_encomenda_produtos_encomendados'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.IntegerField(default=0, help_text='Desconto em porcentagem (0 a 100)'),
        ),
    ]
