# Generated by Django 5.1.4 on 2024-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=200)),
                ('avaliação_dos_Chefs', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_do_produto', models.ImageField(blank=True, null=True, upload_to='Novidades')),
            ],
        ),
    ]
