# Generated by Django 5.1.4 on 2025-01-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_foto_do_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Cartão_Fidelidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='avaliação_da_padaria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
