# Generated by Django 5.1.4 on 2025-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cartaofidelidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_de_telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
