# Generated by Django 5.1.4 on 2025-02-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_foto_do_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartaoFidelidate',
            new_name='CartaoFidelidade',
        ),
    ]
